METHOD:
  method: 'Finetune'
  episodic_training: False
  iter: 100
  finetune_lr: 0.01
  temp: 10
  finetune_all_layers: False
  eval_metrics: ['Acc', 'XEnt']
  finetune_cosine_head: True
  finetune_weight_norm: True
  hyperparams: ['method', 'arch', 'base_source', 'test_source', 'finetune_all_layers']

DATA:
  image_size: 126
